export interface User {
  id: number;
  login: string;
  email: string;
  firstName?: string;
  lastName?: string;
  roles: string[];
  activated: boolean;
  createdDate: string;
}

export const mockUsers: User[] = [
  {
    id: 1,
    login: "admin",
    email: "admin@example.com",
    firstName: "Admin",
    lastName: "User",
    roles: ["ROLE_ADMIN", "ROLE_USER"],
    activated: true,
    createdDate: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    login: "superadmin",
    email: "superadmin@example.com",
    firstName: "Super",
    lastName: "Admin",
    roles: ["ROLE_SUPER_ADMIN", "ROLE_ADMIN", "ROLE_USER"],
    activated: true,
    createdDate: "2024-01-10T08:30:00Z",
  },
  {
    id: 3,
    login: "john.doe",
    email: "john.doe@example.com",
    firstName: "John",
    lastName: "Doe",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-01T14:20:00Z",
  },
  {
    id: 4,
    login: "jane.smith",
    email: "jane.smith@example.com",
    firstName: "Jane",
    lastName: "Smith",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-05T09:15:00Z",
  },
  {
    id: 5,
    login: "manager",
    email: "manager@example.com",
    firstName: "Manager",
    lastName: "User",
    roles: ["ROLE_ADMIN", "ROLE_USER"],
    activated: true,
    createdDate: "2024-01-20T11:45:00Z",
  },
  {
    id: 6,
    login: "developer",
    email: "developer@example.com",
    firstName: "Dev",
    lastName: "User",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-10T16:30:00Z",
  },
  {
    id: 7,
    login: "test.user",
    email: "test@example.com",
    firstName: "Test",
    lastName: "User",
    roles: ["ROLE_USER"],
    activated: false,
    createdDate: "2024-02-15T10:00:00Z",
  },
  {
    id: 8,
    login: "alice.brown",
    email: "alice.brown@example.com",
    firstName: "Alice",
    lastName: "Brown",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-08T13:22:00Z",
  },
  {
    id: 9,
    login: "bob.wilson",
    email: "bob.wilson@example.com",
    firstName: "Bob",
    lastName: "Wilson",
    roles: ["ROLE_ADMIN", "ROLE_USER"],
    activated: true,
    createdDate: "2024-01-25T09:10:00Z",
  },
  {
    id: 10,
    login: "charlie.davis",
    email: "charlie.davis@example.com",
    firstName: "Charlie",
    lastName: "Davis",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-12T15:45:00Z",
  },
  {
    id: 11,
    login: "diana.miller",
    email: "diana.miller@example.com",
    firstName: "Diana",
    lastName: "Miller",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-03T11:30:00Z",
  },
  {
    id: 12,
    login: "edward.garcia",
    email: "edward.garcia@example.com",
    firstName: "Edward",
    lastName: "Garcia",
    roles: ["ROLE_USER"],
    activated: false,
    createdDate: "2024-02-18T08:15:00Z",
  },
  {
    id: 13,
    login: "fiona.rodriguez",
    email: "fiona.rodriguez@example.com",
    firstName: "Fiona",
    lastName: "Rodriguez",
    roles: ["ROLE_ADMIN", "ROLE_USER"],
    activated: true,
    createdDate: "2024-01-28T14:50:00Z",
  },
  {
    id: 14,
    login: "george.martinez",
    email: "george.martinez@example.com",
    firstName: "George",
    lastName: "Martinez",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-07T12:20:00Z",
  },
  {
    id: 15,
    login: "helen.anderson",
    email: "helen.anderson@example.com",
    firstName: "Helen",
    lastName: "Anderson",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-14T10:35:00Z",
  },
  {
    id: 16,
    login: "ivan.taylor",
    email: "ivan.taylor@example.com",
    firstName: "Ivan",
    lastName: "Taylor",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-01T09:00:00Z",
  },
  {
    id: 17,
    login: "julia.thomas",
    email: "julia.thomas@example.com",
    firstName: "Julia",
    lastName: "Thomas",
    roles: ["ROLE_ADMIN", "ROLE_USER"],
    activated: true,
    createdDate: "2024-01-30T16:10:00Z",
  },
  {
    id: 18,
    login: "kevin.jackson",
    email: "kevin.jackson@example.com",
    firstName: "Kevin",
    lastName: "Jackson",
    roles: ["ROLE_USER"],
    activated: false,
    createdDate: "2024-02-20T07:45:00Z",
  },
  {
    id: 19,
    login: "laura.white",
    email: "laura.white@example.com",
    firstName: "Laura",
    lastName: "White",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-09T13:55:00Z",
  },
  {
    id: 20,
    login: "michael.harris",
    email: "michael.harris@example.com",
    firstName: "Michael",
    lastName: "Harris",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-11T15:20:00Z",
  },
  {
    id: 21,
    login: "nancy.clark",
    email: "nancy.clark@example.com",
    firstName: "Nancy",
    lastName: "Clark",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-06T11:10:00Z",
  },
  {
    id: 22,
    login: "oscar.lewis",
    email: "oscar.lewis@example.com",
    firstName: "Oscar",
    lastName: "Lewis",
    roles: ["ROLE_ADMIN", "ROLE_USER"],
    activated: true,
    createdDate: "2024-01-22T10:25:00Z",
  },
  {
    id: 23,
    login: "patricia.robinson",
    email: "patricia.robinson@example.com",
    firstName: "Patricia",
    lastName: "Robinson",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-13T14:40:00Z",
  },
  {
    id: 24,
    login: "robert.walker",
    email: "robert.walker@example.com",
    firstName: "Robert",
    lastName: "Walker",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-04T08:50:00Z",
  },
  {
    id: 25,
    login: "sarah.young",
    email: "sarah.young@example.com",
    firstName: "Sarah",
    lastName: "Young",
    roles: ["ROLE_USER"],
    activated: true,
    createdDate: "2024-02-16T12:30:00Z",
  },
];

